Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      System: Warning

ServiceOptions:
  ServiceName: detroitHarps-api
  LogFolder: "/tmp/detroitharps/api/"
  ClientLogFolder: "/tmp/detroitharps/client/"
  BindUrl: http://localhost:5000
  EnableConsole: true