## test env connection strings, ok to check in
ConnectionStrings:
  Default: "Host=157.230.51.199;Database=detroitharps_dev;Username=detroitharps;Password=password"

Auth0:
  Domain: "angband.auth0.com"
  Authority: "https://angband.auth0.com"
  ApiIdentifier: "https://dev.api.detroitharps.com"