## test env connection strings, ok to check in
ConnectionStrings:
  Default: "Host=157.230.51.199;Database=detroitharps_dev;Username=detroitharps;Password=password"

Auth0:
  Domain: "angband.auth0.com"
  Authority: "https://angband.auth0.com"
  ApiIdentifier: "https://dev.api.detroitharps.com"

Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      System: Warning

ServiceOptions:
  ServiceName: detroitHarps-api
  LogFolder: "/tmp/detroitharps/api/"
  BindUrl: http://localhost:5000
  EnableConsole: true