## test env connection strings, ok to check in
ConnectionStrings:
  Default: "Host=localhost;Database=detroitharps_dev;Username=detroitharps;Password=password"

Auth0:
  Domain: "angband.auth0.com"
  Authority: "https://angband.auth0.com"
  ApiIdentifier: "https://dev.api.detroitharps.com"


S3:
  Url: "https://nyc3.digitaloceanspaces.com"
  BucketName: "detroitharps-app-storage"

Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      System: Warning

ServiceOptions:
  ServiceName: detroitHarps-api
  LogFolder: "/detroitharps/logs/api/"
  ClientLogFolder: "/detroitharps/logs/client/"
  BindUrl: http://localhost:5000
  CorsAllowUrls:
      - http://localhost:4200
      - https://dev.detroitharps.com

# test email, dont really care if password is public
EmailSettings:
    Email: "detroitharps.test@gmail.com"
    Password: "testemail"
    RecievingEmail: "detroitharps@gmail.com"