FROM ubuntu

RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh

RUN chmod +x dotnet-install.sh 

RUN ./dotnet-install.sh -c 2.2
ENV PATH="/root/.dotnet/:$PATH"
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1