version: 2
general:
  branches:
    only:
      - master
      - api
      - client
jobs:
  api:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: testing dotnet version
          command: dotnet --info
      - run:
          name: Restore
          command: dotnet restore api/Api.sln
      - run:
          name: Build
          command: dotnet build api/Api.sln
      - run:
          name: Test
          command: scripts/dotnet-test.sh
      - run:
          name: Publish Repository.Migrator
          command: dotnet publish api/src/Repository.Migrator/Repository.Migrator.csproj -c RELEASE -o /root/project/publish/Repository.Migrator
      - run:
          name: Publish Repository.Dataloader
          command: dotnet publish api/src/Repository.Dataloader/Repository.Dataloader.csproj -c RELEASE -o /root/project/publish/Repository.Dataloader
      - run:
          name: Publish Service
          command: dotnet publish api/src/Service/Service.csproj -c RELEASE -o /root/project/publish/Service
      - run:
          name: Copy and Deploy
          command: scripts/circleci-api.sh
  client:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: testing npm version
          command: npm -v
      - run:
          name: Npm install 
          command: cd client && npm install
      - run:
          name: Build Copy Deploy
          command: scripts/circleci-site.sh
          
workflows:
  version: 2
  build_api_client:
    jobs:
      - api:
          filters:
            branches:
              only:
                - api
                - master
      - client:
          filters:
            branches:
              only:
                - client
                - master