version: 2
general:
  branches:
    only:
      - master
      - api
      - client
jobs:
  api:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: testing dotnet version
          command: dotnet --info
      -run:
          name: DataAccess.Test
          command: dotnet test api/test/DataAccess.Test/DataAccess.Test.csproj
      -run:
          name: Business.Test
          command: dotnet test api/test/Business.Test/Business.Test.csproj
  client:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: testing npm version
          command: npm -v

workflows:
  version: 2
  build_api_client:
    jobs:
      - api
      - client