version: 2
general:
  branches:
    only:
      - master
      - api
      - client
jobs:
  api:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: testing dotnet version
          command: dotnet --info
      - run:
          name: Restore
          command: dotnet restore api/Api.sln
      - run:
          name: Build
          command: dotnet build api/Api.sln
      - run:
          name: DataAccess.Test
          command: dotnet test api/test/DataAccess.Test/DataAccess.Test.csproj
      - run:
          name: Business.Test
          command: dotnet test api/test/Business.Test/Business.Test.csproj
      - run:
          name: Publish Repository.Migrator
          command: dotnet publish api/src/Repository.Migrator/Repository.Migrator.csproj -o ./publish/Repository.Migrator
      - run:
          name: Publish Repository.Dataloader
          command: dotnet publish api/src/Repository.Dataloader/Repository.Dataloader.csproj -o ./publish/Repository.Dataloader
      - run:
          name: Publish Service
          command: dotnet publish api/src/Service/Service.csproj -o ./publish/Service
      - run:
          name: Add Server to known_hosts
          environment:
            PUBLIC_KEY: "|1|Zj1eT2OEObP2Ovh83T7dKNqaIqA=|lqu/pS4Wey1FHtQho7kFy2NJYJs= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFmUQu3aTDNgYdhAtuUDQxq+OLFHAQ0Y6XCtpam+ZNZzos4p7s7MBbjPsyQeKKiUimwn11C3Xd8tednO8TikJOg="
          command: echo $PUBLIC_KEY >> ~/.ssh/known_hosts
      - run:
          name: Clear old files
          command: ssh root@45.33.89.196 "if [ -d /deploy/api/ ]; then rm -rf /deploy/api/*; fi"
      - run:
          name: Copy to dev server
          command: scp -r ./publish/* root@45.33.89.196:/deploy/api/
  client:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: testing npm version
          command: npm -v

workflows:
  version: 2
  build_api_client:
    jobs:
      - api
      - client