## yml and not yaml becuase circleci is picky
version: 2

general:
  branches:
    only:
      - master
      - dev

jobs:
  checkout:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: ~/detroitharps
    steps:
      - checkout
      - save_cache:
          key: checkout-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/detroitharps
  test:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: ~/detroitharps
    steps:
      - restore_cache:
          key: checkout-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: ./scripts/dotnet-test.sh
  publish:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: ~/detroitharps
    steps:
      - restore_cache:
          key: checkout-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Publish DataAccess.Migrator
          command: dotnet publish src/DataAccess.Migrator/ -c RELEASE -o ~/detroitharps/publish/DataAccess.Migrator
      - run:
          name: Publish Api
          command: dotnet publish src/Api/ -c RELEASE -o ~/detroitharps/publish/Api
      - run:
          name: Copy Configuration
          command: cp -r ~/detroitharps/configuration ~/detroitharps/publish
      - save_cache:
          key: publish-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/detroitharps/publish
  deploy-dev:
    docker:
      - image: microsoft/dotnet:sdk
        environment:
          IP_ADDRESS: '157.230.51.199'
          SSH_ADDR: 'detroitharps@157.230.51.199'
          DEPLOY_FOLDER: '/detroitharps/publish'
          RUN_FOLDER: '/detroitharps/application'
    working_directory: ~/detroitharps
    steps:
      - restore_cache:
          key: publish-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Copy SSH fingerprint to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $IP_ADDRESS >> ~/.ssh/known_hosts
      - run:
          name: Copy Publish Folder to Server
          command: |
            ssh $SSH_ADDR "if [ -d $DEPLOY_FOLDER ]; then rm -rf $DEPLOY_FOLDER; fi"
            ssh $SSH_ADDR "mkdir -p $DEPLOY_FOLDER"
            scp -r ./publish/* $SSH_ADDR:$DEPLOY_FOLDER
      - run:
          name: Copy to Run Folder
          command: |
            ssh $SSH_ADDR "if [ -d $RUN_FOLDER ]; then rm -rf $RUN_FOLDER; fi"
            ssh $SSH_ADDR "mkdir -p $RUN_FOLDER"
            ssh $SSH_ADDR "cp -r $DEPLOY_FOLDER/* $RUN_FOLDER/"
      - run:
          name: Install Service
          command: |
            ssh $SSH_ADDR "sudo ln -sf $DEPLOY_FOLDER/configuration/dev/systemd/detroitharps-api.service /etc/systemd/system/detroitharps-api.service"
            ssh $SSH_ADDR "sudo systemctl restart detroitharps-api.service"
      - run:
          name: Install Service
          command: |
            ssh $SSH_ADDR "sudo ln -sf $DEPLOY_FOLDER/configuration/dev/nginx/dev.api.detroitharps.com /etc/nginx/sites-enabled/dev.api.detroitharps.com"
            ssh $SSH_ADDR "sudo systemctl restart nginx"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - dev
                - master
      - test:
          requires:
            - checkout
      - publish:
          requires:
            - checkout
      - deploy-dev:
          requires:
            - publish
            - test
          filters:
            branches:
              only:
                - dev
