version: 2
general:
  branches:
    only:
      - master
      - api
      - client
jobs:
  api:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: testing dotnet version
          command: dotnet --info
  client:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: testing npm version
          command: npm -v
      - run:
          name: Npm install 
          command: cd client && npm install
      - run:
          name: Build 
          command: cd client && npm run build-dev -- --aot
      - run:
          name: Add Server to known_hosts
          environment:
            PUBLIC_KEY: "|1|Zj1eT2OEObP2Ovh83T7dKNqaIqA=|lqu/pS4Wey1FHtQho7kFy2NJYJs= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFmUQu3aTDNgYdhAtuUDQxq+OLFHAQ0Y6XCtpam+ZNZzos4p7s7MBbjPsyQeKKiUimwn11C3Xd8tednO8TikJOg="
          command: echo $PUBLIC_KEY >> ~/.ssh/known_hosts
      - run:
          name: Clear old files
          command: ssh root@45.33.89.196 "if [ -d /deploy/client ]; then rm -rf /deploy/client; fi"
      - run:
          name: Create folder to publish to
          command: ssh root@45.33.89.196 "mkdir -p /deploy/client"
      - run:
          name: Copy to dev server
          command: scp -r client/dist root@45.33.89.196:/deploy/client/
      - run:
          name: Copy scripts to dev server
          command: scp -r /scripts root@45.33.89.196:/deploy/client/
      - run:
          name: Deploy
          command: ssh root@45.33.89.196 "/deploy/client/scripts/dev-deploy-client.sh"

workflows:
  version: 2
  build_api_client:
    jobs:
      - api
      - client