## yml and not yaml becuase circleci is picky
version: 2

general:
  branches:
    only:
      - master
      - dev
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: testing dotnet version
          command: dotnet --info
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: scripts/dotnet-build.sh
      - run:
          name: Test
          command: scripts/dotnet-test.sh
      - run:
          name: Publish DataAccess.Migrator
          command: dotnet publish src/DataAccess.Migrator/ -c RELEASE -o /root/project/publish/DataAccess.Migrator
      - run:
          name: Publish Api
          command: dotnet publish src/Api/ -c RELEASE -o /root/project/publish/Api
      - run:
          name: Deploy
          command: .circleci/scripts/circleci-deploy.sh
      - run:
          name: Install
          command: .circleci/scripts/circleci-install.sh