// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DetroitHarps.DataAccess.Migrator.Migrations
{
    public partial class RemovingUnnecessaryPaymentColumns : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "PaymentInformation_PaymentTimestamp",
                table: "Registration");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "PaymentInformation_PaymentTimestamp",
                table: "Registration",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
        }
    }
}
