// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DetroitHarps.DataAccess.Migrator.Migrations
{
    public partial class AddingExplicitIdToRegistrationChild : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "insert_timestamp",
                table: "RegistrationChild",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "update_timestamp",
                table: "RegistrationChild",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "insert_timestamp",
                table: "RegistrationChild");

            migrationBuilder.DropColumn(
                name: "update_timestamp",
                table: "RegistrationChild");
        }
    }
}
