// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace DetroitHarps.DataAccess.Migrator.Migrations
{
    public partial class AddingShowTimeFlagToEvent : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "ShowTime",
                table: "Event",
                nullable: false,
                defaultValue: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ShowTime",
                table: "Event");
        }
    }
}
